name: CI/CD Pipeline

# Trigger on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Linting and Code Quality
    - name: Run flake8
      run: flake8 .

    # Step 5: Run Unit and Integration Tests
    - name: Run tests with pytest
      run: pytest

    # Step 6: Build Docker Image
    - name: Build Docker image
      run: docker build -t flask-sentence-transformer .

    # Step 7: Run Docker Container and Test
    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name api-test flask-sentence-transformer
        sleep 10  # Allow the container to start up

    # Step 8: Validate Deployment
    - name: Validate API health check
      run: |
        curl http://localhost:8000/health

    # Step 9: Cleanup Docker Resources
    - name: Cleanup Docker resources
      run: |
        docker stop api-test
        docker rm api-test
